name: CI

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          scope: "@danreeves"
      - run: "npm i -g lerna"
      - run: "lerna publish from-package --yes --no-verify-access"

  deploy:
    runs-on: ubuntu-latest

    env:
      NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm i -g lerna
      - run: lerna bootstrap --hoist
      - run: npm run clean
      - run: npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: packages/app-shell/dist
